### ISSUE TITLE
Fails to decode public keys for Counterparty transaction outputs

### ISSUE THREAD

**Issue by jprupp** [jprupp/haskoin-core#152]
This transaction contains an output that has an invalid second public key:

https://insight.bitpay.com/tx/34040cf4494f3bc9c06befb6850a89e877c56e7bbaa77a6917820cfa6c7989d9

This output cannot be decoded by Haskoin because the first byte of one public key is not 2, 3 or 4.

**Comment by m0dev76** [comment]
The script in question is:

```
OP_1 02a699dcda8d38ca4aa8e42045485b6b101d9c45c4af638c0e94bdf9ba09bd593e 1c434e54525052545900000000000000000001a7d1000000000149ceaa00000000 OP_2 OP_CHECKMULTISIG
```

**Comment by m0dev76** [comment]
We don't decode scripts unless you need to evaluate the script. If you want to evaluate that script, then Haskoin doesn't know what the second key is because it is not in compressed form (starting with 2 or 3) or in uncompressed form (starting with 4). So Haskoin doesn't know how to get the point on the curve represented by that key. Is this something special to counterparty?

**Comment by jprupp** [comment]
Bitcoin Core considers this output spendable since it requires a single signature, even while it has two keys. It will ignore the invalid keys and only consider signatures performed against the valid key. I am not sure if the transaction would be equally valid if the keys were in different order.

The space for the extra key is used for Counterparty metadata. This system was created before OP_RETURN became available. It seems that the Bitcoin Core scripting engine will parse keys lazily, not even looking at invalid ones if it is not necessary to determine the validity of the transaction. It would be good to look at the scripting engine code directly to understand these edge cases.

**Comment by jprupp** [comment]
I don't think we should support this anymore.
