### ISSUE TITLE
Implement BIP65 checks for SPV

### ISSUE THREAD

**Issue by m0dev76** [jprupp/haskoin-core#199]

**Comment by tphyahoo** [comment]
Is anyone working on this?

If not I may begin.  At least I could gather test vectors from other implementations.

(I may have immediate use for this.)

**Comment by tphyahoo** [comment]
Is this task merely what is described at 

https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki#SPV_Clients 

? 

That is, just that spv clients should reject nVersion < 4 now, since bip65 has been in enforcement for some time now. (Or specifically to reject < 4  if 950 out of 1000 preceding blocks have nVersion >= 4)

**Comment by jprupp** [comment]
Go ahead.

**Comment by jprupp** [comment]
Old wallet is being deprecated. Perhaps this will be relevant for the new node code. I'll close for now.
