### ISSUE TITLE
Send transactions with time locked funds (BIP-65)

### ISSUE THREAD

**Issue by jprupp** [jprupp/haskoin-core#214]
A new transaction command, under the "transactions" section in help.

sendtimelocked acc addr amount unlockBlock [-S]

funds are spendable after unlockBlock appears in the blockchain.

**Comment by tphyahoo** [comment]
Is anyone working on this?

If not I may begin (I have probable use for it).  My first move would be to wrangle bip65 test vectors from

https://github.com/petertodd/bitcoin/commit/ab0f54f38e08ee1e50ff72f801680ee84d0f1bf4 (linked from bip65 spec)

into 

https://github.com/haskoin/haskoin/blob/master/haskoin-core/tests/Network/Haskoin/Transaction/Units.hs

which seems to be basically cribbed from satoshi bitcoin tx_valid.json and tx_invalid.json

UPDATE: I suppose it would be better to use vectors repo bitcoin/bitcoin instead of petertodd/bitcoin, as more up to date.  

Also, it's a pity we can't just copy tx_valid.json and tx_invalid.json (and many other test data files there as well potentialy) from bitcoin repo and use these for tests directly, rather than staying in sync by manual surgery.  Perhaps there would be some way to achieve that.

**Comment by tphyahoo** [comment]
transaction tests now include failing vectors for cltv, copied from bitcoin core test suite (where the vectors pass). (from #255)

**Comment by jprupp** [comment]
Script interpreter code is outdated. Work needs to be done update it or remove it from `haskoin-core`. I'll close this bug because it is just one part of changes that should be done to the script interpreter.
