### ISSUE TITLE
Support hardware wallet for offline signing

### ISSUE THREAD

**Issue by tphyahoo** [jprupp/haskoin-core#232]
this was closed in historical repo.  Reopening, because I still think this is a good idea.

historical issue thread: https://github.com/haskoin/haskoin-wallet/issues/131

**Comment by wraithm** [comment]
My personal opinion here is that all haskoin needs is a function to add signatures to an existing transaction, so that any haskoin independent signing procedure could be supported. Haskoin probably shouldn't support hardware wallets directly. That could be implemented as a separate library for each hardware vendor (ie. `haskoin-trezor`, `haskoin-ledger`, etc). Right now, adding signatures to an unsigned transaction is highly coupled to the `signTx` function. Really, we need some function `addSignature :: Signature -> Tx -> Tx`.

**Comment by wraithm** [comment]
Maybe just a simple wrapper function for `buildInput` would be all that's necessary.

**Comment by tphyahoo** [comment]
WraithM, re potential wrapper function: just some breadcrumbs for future follow-up. 

getOfflineTxData gets signable data from wallet database (including inputs).  This is used in the guts of cmdGetOffline, which is how haskoin wallet fetches the inputs for siging offline transactions.  cmdSignOffline performs the signatures, with data produced from cmdGetOffline.

```
getOfflineTxData ::
  (transformers-0.4.2.0:Control.Monad.IO.Class.MonadIO m,
   MonadThrow m, MonadBase IO m, MonadResource m) =>
  AccountId
  -> TxHash
  -> persistent-2.2.4:Database.Persist.Sql.Types.SqlPersistT
       m (OfflineTxData, [InCoinData])
    -- Defined at Network/Haskoin/Wallet/Transaction.hs:1012:1

*Network.Haskoin.Wallet.Client.Commands> :i cmdGetOffline
cmdGetOffline :: String -> String -> Handler ()
    -- Defined at Network/Haskoin/Wallet/Client/Commands.hs:393:1
*Network.Haskoin.Wallet.Client.Commands> :i cmdSignOffline
cmdSignOffline :: String -> String -> String -> Handler ()
    -- Defined at Network/Haskoin/Wallet/Client/Commands.hs:406:1

cmdSignOffline :: String -> String -> String -> Handler ()
cmdSignOffline name txStr datStr = .....

cmdGetOffline :: String -> String -> Handler ()
cmdGetOffline name tidStr = .....

```

I'm not sure if the inputs to be signed can be derived from a Tx value.  If so, wrapper function is the right thing.  Otherwise it might be necessary to hit the wallet database. (I'm currently puzzling over code. Maybe one of the main devs can chime in.)

**Comment by tphyahoo** [comment]
Also, if the inputs to be signed CAN be derived from a transaction, it would seem better if 

 cmdSignOffline merely used the data from a Tx to do the signature, rather than a Tx plus a bunch of inputs, which is what it seems to be doing now. (Increases purity).

```
cmdSignOffline :: String -> String -> String -> Handler ()
cmdSignOffline name txStr datStr = case (txM, datM) of
    (Just tx, Just dat) -> do
        masterM <- getSigningKeys name
        resE <- sendZmq (PostOfflineTxR (pack name) masterM tx dat)
        handleResponse resE $ \(TxCompleteRes tx' c) -> do
            liftIO $ putStrLn $ unwords
                [ "Tx      :", cs $ encodeHex $ encode' tx' ]
            liftIO $ putStrLn $ unwords
                [ "Complete:", if c then "Yes" else "No" ]
    _ -> error "Could not decode input data"
  where
    datM = decode . cs =<< decodeHex (cs datStr)
    txM  = decodeToMaybe =<< decodeHex (cs txStr)
```

That is to say, datStr should be eliminated from the above function if possible.  And if it can't be eliminated, I guess a database lookup in the IO monad is required for signing.

**Comment by jprupp** [comment]
I'm working on changes to move the whole signing process to the client. I'll remove all traffic of privileged data from the database. There will be no master private key associated with accounts in the database, nor remote calls that can perform signatures or generate private keys server-side.

The idea behind it is that the client is now fully responsible for managing keys, or for delegating key management to another subsystem, which can be a hardware wallet or an HSM. Whatever functions may be needed from the Haskoin libraries in order to perform signatures will be exposed appropriately.

I have not started this work yet, but will start soon.

**Comment by wraithm** [comment]
Thanks @xenog! You still need to expose some sort of access to `buildInput` in haskoin-core, right? What's that going to look like? In [my commit](https://github.com/WraithM/haskoin/commit/566d3ddf82dca284a68c103fca6cb6c63e4e466b), I simply added `buildInput` to the module exports for `Network.Haskoin.Transaction`, and that solved my problem.

**Comment by wraithm** [comment]
@xenog, It doesn't seem to be possible to modify inputs of an existing transaction any more because `Tx`'s record accessors were hidden somewhere between `haskoin-core-0.3` and `0.4`. I could modify my hardware signature function to deconstruct the `Tx` via `txIn` and `txOut` then reconstruct the `Tx` via `createTx`. Just out of curiosity, why did you remove the `Tx` type's record accessors?

**Comment by jprupp** [comment]
For performance reasons now the transaction hash is stored as [one of the data elements](https://github.com/haskoin/haskoin/blob/master/haskoin-core/Network/Haskoin/Transaction/Types.hs#L136). Replacing a field directly in a transaction would lead to an invalid data structure if the hash is not recomputed as well. That is why you are now forced to use the constructor function.

**Comment by wraithm** [comment]
Thanks! That makes a lot of sense.

**Comment by jprupp** [comment]
I'll close this for now. The old wallet is being deprecated.
