### ISSUE TITLE
Communicating with Bitcoin Core/RPC

### ISSUE THREAD

**Issue by GildedHonour** [jprupp/haskoin-core#299]
I run the full bitcoin node on a server and I want to create a web interface for it in haskell. Perphans only via REST API, but it doesn't matter. In this way, I want to be able to communicate with the bitcoin core/full node via RPC using Haskell. Do I understand correctly that this library -- haskoin -- won't allow me to do that?

**Comment by GildedHonour** [comment]
If so, what Haskell client for Core/RPC will you recommend me? I can't find any which is more or less up to date and complete.

**Comment by runeksvendsen** [comment]
Hello sir

You are correct, Haskoin is an implementation of the Bitcoin protocol - just like Bitcoin Core. So it's an alternative to Bitcoin Core, rather than a way to communicate with it.

However, I have a fork of the `bitcoin-api` package (https://github.com/runeksvendsen/haskell-bitcoin-api) which adds a number of supported RPC calls, plus fixes exception handling. It should be fairly easy for you to add new RPC calls, although a lot are supported already.

I've also thrown together a server which uses this package, and exposes certain Bitcoin Core RPC calls via a REST API: https://github.com/runeksvendsen/blockchain-restful-address-index. It works good as an example on how easy it is to add a REST interface to anything in Haskell using Servant, but it could probably use a rewrite, mostly for proper exception handling (there are a lot of `error`s).

**Comment by GildedHonour** [comment]
Are you working on https://github.com/runeksvendsen/haskell-bitcoin-api? Or should I fork it and continue doing what hasn't been done yet?

**Comment by runeksvendsen** [comment]
Yes, that fork of mine is active. Please fork my fork, build your work on top of that, and submit pull requests back to me. 

In the meantime, I will write an email to Hackage and the original author, asking whether I can take over as maintainer of this package, so the code doesn't have to live on just GitHub.

**Comment by GildedHonour** [comment]
How about if I fork it and take it over?

**Comment by runeksvendsen** [comment]
Hi Alex

Thank you for reminding me about this, I had forgotten to get back to you. I've spoken with @solatis, and he gave me push access to his repo, so I've merged my changes, and you should fork from there (although the two repos are now the same, so it shouldn't matter where you fork from).

**Comment by GildedHonour** [comment]
@runeksvendsen thx.
I'll change it quite a bit, specifically formatting, as well as add new methonds and other stuff, therefore I'll create a new repository and will mention that it's based on your code.

**Comment by runeksvendsen** [comment]
@GildedHonour Great! I completely agree that it's ripe for a rewrite, so I'm happy to hear you're up for the task. I look forward to seeing what comes out of it.

**Comment by jprupp** [comment]
I will close this ticket. Reopen if you wish to continue this discussion here.
