### ISSUE TITLE
makeXPrvKey exception due to `getNetwork`

### ISSUE THREAD

**Issue by charlescrain** [jprupp/haskoin-core#353]
Hello,

I'm new to this library and playing with some of the crypto from `haskcoin/core`. 

I am curious why `makeXPrvKey` is calling the `getNetwork` function. As far as I understand, the function is pure  and only performs the necessary crypto to build the Extended Key. From the error posted below it appears to need an IO reference to a network. I've done my best to locate where `getNetwork` is called with no luck.

My question is:
* When generating extended keys is there some dependency on the network type? (I noticed that the Network type has seeds, so maybe these are used in generating the key?)

I am new to Extended Keys and this library so pardon my confusion if I am missing something obvious.

Here is what I've done to create the key in GHCI:

```
>let (Right seed)  = mnemonicToSeed "" "habit maze snack give case old speak grid cram maze era glad"
>makeXPrvKey seed
*** Exception: Use Network.Haskoin.Constants.setNetwork
CallStack (from HasCallStack):
  error, called at /Users/charlescrain/dev/haskoin/haskoin-core/src/Network/Haskoin/Constants.hs:107:13 in main:Network.Haskoin.Constants
```

Steps to repoduce:
* `stack ghci haskcoin-core`
* `let (Right seed)  =mnemonicToSeed "" "habit maze snack give case old speak grid cram maze era glad"`
* `makeXPrvKey seed`

Apologies if this isn't the appropriate place to post this question.

Thanks,
Charles

**Comment by sha49** [comment]
I think you are missing to set the network that you will use. (bitcoin, bch, testnet... ?) This will have effects on how you serialise keys, addresses etc.. this is probably why is required.

**Comment by sha49** [comment]
Try calling any of these guys on your main before you start doing anything.

https://github.com/haskoin/haskoin/blob/b80099c0a5ef96fc85d27beaaf81a2ee111803c2/haskoin-core/src/Network/Haskoin/Constants.hs#L80-L90

**Comment by charlescrain** [comment]
@sha49 Thanks for the suggestion I had tried that but I have a feeling that since I'm using the repl it wasn't working. Thanks for the advice

**Comment by charlescrain** [comment]
I'm curious why this IO reference for the Network is used. Seems confusing to have a hidden dependency in functions such as `makeXPrvKey`. If there has been any discussion around this would appreciate being pointed in the right direction. Thanks!

**Comment by runeksvendsen** [comment]
@charlescrain I didn't write the code, so I can't say for sure, but I assume this design choice was made because applications rarely (if ever) need to mix different network types. E.g. a wallet is either run on `testnet` or on `prodnet`, but not both at the same time. If using different networks at the same time were useful, a monad probably would have made more sense (as @sha49 mentions, the `Network` is a necessary parameter to many functions in `haskoin`, since the network byte is incorporated into the serialization format of many core data types).

If I recall correctly, at some point the network was automatically set to `prodnet`, which avoided this exception. But it is now mandatory to explicitly set the network on startup.

**Comment by charlescrain** [comment]
@runeksvendsen Thanks!

**Comment by charlescrain** [comment]
Found more details here: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Serialization_format

**Comment by jprupp** [comment]
Hello,

At some point at the beginning, when writing the Haskoin library, we had these functions that took the network as an argument. Pretty much every function at this point needed this argument. We changed everything to use a reader monad where the network was implicit, but made using the library more complicated than when passing the parameter explicitly. We needed another approach.

Since the network is needed by so many functions, and when writing code at first there is a tendency to hard-code things to expedite work, it happened that sometimes we would code a function and then find that it worked when we used a network, but fail when using another network. We figured that often we forgot to replace some hard-coded network somewhere. Also, rarely we needed to use more than one network at a time during the lifetime of a running program using this library.

We chose to make the network a global set-only parameter, and if a function was to be called that required this global parameter to be set, but it wasn't, then the program would throw an exception. It used to be the case that the main Bitcoin network was set by default if a function used a network constant, but that sometimes caused problems as it was difficult to ascertain which functions could be safely called before setting the network without them setting the network inadvertently as a side effect.

If needed for any reason, we can go back to passing the network explicitly as an argument to every function that requires it, and get rid of the whole impure global network setting. On the days I am reminded that we use a global value for the network I feel like an infidel in the church of functional purity.

If anyone alternatively wants to change everything to remove that global value, submit a pull request. I don't mind about backwards compatibility.

Greetings
