### ISSUE TITLE
Using Text instead of ByteString for human readable strings

### ISSUE THREAD

**Issue by wraithm** [jprupp/haskoin-core#358]
I love the work that's going into haskoin-core 1.0.0! This is amazing. My only complaint is that functions like `txHashToHex :: TxHash -> ByteString` and `addrToString :: Address -> Maybe ByteString` use implicitly utf8-encoded `ByteString`s instead of `Text`. I end up using wrappers around these functions in my code. It would be nice if those functions just did `Text` directly because they're explicitly utf encoded human-readable strings, which is what `Text` is for.

What does everybody think about this?

**Comment by wraithm** [comment]
@xenog @plaprade

**Comment by jprupp** [comment]
The reason I used `ByteString` for addresses and hex-encoded strings is that they comprise only characters that fit in an eight-bit word (low Unicode). It is thus wasteful to use `Text` or `[Char]`, as those take up at least twice as much memory (16 or 32 bits) to represent every single character, plus the required overhead of convertion when needed.

I was trying to optimise the code as much as I could back when I chose `ByteString` for these data types, but I am now convinced that the string representations and conversion for these types are not performance bottlenecks that matter, and I would gladly switch `Text` if that is convenient.

**Comment by wraithm** [comment]
I'd be happy to make a PR for it.

**Comment by wraithm** [comment]
@xenog I just tried to clone `haskoin-core` to build, and I got this error on building `secp256k1`:

```secp256k1-1.1.2: configure (lib)
Configuring secp256k1-1.1.2...
Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: Missing dependency on a foreign
library:
* Missing (or bad) C library: secp256k1
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

Do I need to have the C library `secp256k1` installed globally to use `haskoin-core`? What do you do for your dev setup?

**Comment by sha49** [comment]
I faced the same issues today. 

Yes, secp256k1 C is a dependency of haskoin core. So, you can clone the repo https://github.com/bitcoin-core/secp256k1 and follow the build steps or you can install `nix` on your machine and then run `stack --nix install` and then the dependencies will be set locally by nix.

**Comment by wraithm** [comment]
So, `nix` is essentially a dependency of the new `haskoin-core` via `secp256k1`... That's a big change! I don't use `nix`.

**Comment by wraithm** [comment]
Why the change? The cabal bundling of the C code from before worked great.

**Comment by sha49** [comment]
Well, it is not mandatory. You either handle the dependencies at your own, like installing secp256k1 by yourself or you use nix. Until now you were responsible for each dependency. Now you have the option to have only nix as dependency and it will get the rest of needed stuff. Both ways are working.

**Comment by wraithm** [comment]
I mean, isn't that somewhat dangerous? What if my local version of `secp256k1` doesn't match with the haskell library? Before, we were pinning a specific version to a hackage release, right? Like, the C lib came with the hackage bundle. Having the versions potentially get out of sync is worrisome to me.

**Comment by sha49** [comment]
I think nix is building a specific version too

https://github.com/haskoin/haskoin-core/blob/master/stack.yaml

but @xenog will explain better his reasons :D

**Comment by jprupp** [comment]
The bundling of the C code from the upstream `secp256k1` library into the Haskell bindings was clumsy at best. I decided to simplify the bindings and have them be just bindings, needing the library to be already present in the system in order to work. That is the way most bindings are written, unless the C code is so simple that Cabal can handle it gracefully.

With Nix integration you may install the Nix package manager in your Linux distribution or Mac, and then have Stack use it to automatically install non-Haskell dependencies for you. You do it by passing the `--nix` flag to the `stack` command when building or testing. This should install the `secp256k1` library for any Haskoin project that requires it, including `haskoin-core`. Look at the `stack.yaml` file of any of the projects and you'll see how this is specified.

**Comment by wraithm** [comment]
I'm curious what was clumsy about how it worked before? It's always worked great for us.

What I'm worried about is a loss of safety. I don't want to have to worry about ABI mismatches between your bindings and whatever version of `secp256k1` is installed.

I understand that some bindings, say `zeromq` or `libpq` for example, have you install the library on your machine first. However, those tend to be very common packages in many package repositories, which is not really the case with libsecp256k1. Yes, some repositories package libsecp256k1, but we will most likely have to package this ourselves.

We still have the issue of binary compatibility. I have experienced deployment pain with the zeromq haskell library specifically operating this way on several Linux distros. Say the standard ubuntu version is different from the haskell library, we then have to do contortions with apt to get them to behave together.

I certainly don't want to deploy Nix to my production machines. It is so much simpler for the user to have pinned C code. I get that Nix is nice, but we currently don't use it. We're not going to switch to Nix any time soon, so we're forced into packaging libsecp256k1 manually... :/

**Comment by jprupp** [comment]
This is a horrible hack:

https://github.com/haskoin/secp256k1-haskell/blob/f460a603fb1dd7534eb5df978790b793cca455c2/Setup.hs

I don't really understand Cabal all that well. What I tried to do there was to introduce some steps to the build process that made calls to external commands. I had issues with that code more than once, especially since Stack does not clone submodules when depending on a Git repository, making testing that code a bit of a nightmare without having a release in Hackage or tweaking my `stack.yaml` and remembering to tweak it back. Cabal is made to build Haskell and it can deal with a small number of well-behaved C files in a Haskell project. The `secp256k1` library is not really that simple. It's not that easy to embed in a Cabal package properly.

I looked at Nix as a way to deal with—at least for now—non-Haskell dependencies. I read the documentation and I am convinced that it is a more elegant way to handle this sort of thing.

The Nix package manager can be installed in any Linux distribution and in MacOS X. It has a model of package management inspired by purely functional programming. It has its own directory structure that lives outside of the Linux FHS. Packages installed via Nix do not interfere in any way with the rest of packages installed in the sysetm. For example: the `secp256k1` library installed for Haskoin is not to be found in any of the LHS directories where Linux expects to find libraries, so they will not inadvertently conflict with stuff you already have. It stays out of your way unless you know that you want to use it.

Here is the output of `ldd ~/.local/bin/haskoin-store` after I installed it using `stack --nix install`. Notice the locations in the filesystem of the libraries linked to the program:

    linux-vdso.so.1 (0x00007ffd3231d000)
    libm.so.6 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/libm.so.6 (0x00007ff3aba11000)
    librocksdb.so.5.11 => /nix/store/17qimprpgxgi2211d4wkqwyr9hikdccg-rocksdb-5.11.3/lib/librocksdb.so.5.11 (0x00007ff3ab223000)
    libz.so.1 => /nix/store/7zbrn4d4bp7m1yqvp6jhy70kxnxpwxkf-zlib-1.2.11/lib/libz.so.1 (0x00007ff3ab007000)
    libsecp256k1.so.0 => /nix/store/7maqx3qapmcp8qiv5cgdc75ff9sng2vp-secp256k1-2017-12-18/lib/libsecp256k1.so.0 (0x00007ff3aade4000)
    libpthread.so.0 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/libpthread.so.0 (0x00007ff3aabc5000)
    librt.so.1 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/librt.so.1 (0x00007ff3aa9bd000)
    libutil.so.1 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/libutil.so.1 (0x00007ff3aa7ba000)
    libdl.so.2 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/libdl.so.2 (0x00007ff3aa5b6000)
    libgmp.so.10 => /nix/store/ykbpjkffv0djffibfrza8n6hf8iyzws3-gmp-6.1.2/lib/libgmp.so.10 (0x00007ff3aa322000)
    libc.so.6 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/libc.so.6 (0x00007ff3a9f6e000)
    /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007ff3abda6000)
    libsnappy.so.1 => /nix/store/a7bg43izj7v5i8j4rcy68m14qgjhnm99-snappy-1.1.7/lib/libsnappy.so.1 (0x00007ff3a9d64000)
    libgflags.so.2.2 => /nix/store/1qbxq5zvpcdcwl8bil9s080plcqfxj9s-google-gflags-2.2.1/lib/libgflags.so.2.2 (0x00007ff3a9b3e000)
    libbz2.so.1 => /nix/store/qvw8f8g0d1i7l4wsj33s5lhlyjwz2an4-bzip2-1.0.6.0.1/lib/libbz2.so.1 (0x00007ff3a992e000)
    liblz4.so.1 => /nix/store/vqqbgx5xm4r2kbh1dg5xdzim64pnia5j-lz4-1.8.2/lib/liblz4.so.1 (0x00007ff3a96f6000)
    libjemalloc.so.2 => /nix/store/1cs9ijlm0k4lpxn0a51zwi7x5i2jcp4y-jemalloc-4.5.0/lib/libjemalloc.so.2 (0x00007ff3a9495000)
    libstdc++.so.6 => /nix/store/6nqk63zypz177ng87gx6r1zl89rlxd11-gcc-7.3.0-lib/lib/libstdc++.so.6 (0x00007ff3a910e000)
    libgcc_s.so.1 => /nix/store/hx54ggnr64g1g0wggdfvgdm42r2bs1kv-glibc-2.27/lib/libgcc_s.so.1 (0x00007ff3a8ef8000)


The dependencies are located in subdirectories of the `/nix/store` hierarchy identified by a hash that represents the package and its dependencies at the particular version that was used when I performed the installation. If I install a different version of the `secp256k1` library for a new package, either via Nix or in system-wide `/usr/local/lib`, it will not overwrite or conflict with this one.

Nix is not active by default in `stack.yaml` because it conflicts with some IDEs that go crazy in the Nix sandbox that Stack uses when it runs. If you do not use `--nix` as a command-line option to Stack, you'll use your regular system and specified directories to find libraries.

I don't intend to return to bundling the C code for the `secp256k1` upstream dependency with the bindings. If you have a project that depends on `secp256k1`, you may want to write a script to build your project by first downloading the `secp256k1` sources, compiling them, copying the files to a library location, and then using that location as argument to `stack` to link them. In fact the script could take care of all non-Haskell dependencies in the same way, and copy them to a project-specific instead of a system-wide directory. That would actually be quite close to what Nix does.

**Comment by wraithm** [comment]
@xenog Thanks for your insights! Makes sense. We'll just package our own secp256k1.
