### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by ProofOfKeags** [jprupp/haskoin-core#371]
I'd like to put some resources behind helping this project be taken seriously as a usable bitcoin implementation. What can I do to improve the current codebase? What features are missing?

**Comment by jprupp** [comment]
Hello Captain,

The Haskoin libraries in this package lack the ability to perform full transaction validation. There was a script engine what was gutted last year because it wasn't being maintained. If someone is brave enough to work on this for all supported networks, it would be great.

Also, as simpler things go: the haskoin-node and haskoin-store packages are short on tests.

Cheers!

**Comment by ProofOfKeags** [comment]
Is the script engine something that can be worked on incrementally? Ideally
I’d do it for Bitcoin first and then add the opcodes for the alts. Also
what degree of commitment are you putting where. Where are your efforts
currently focused?

**Comment by jprupp** [comment]
Currently I am focused on the haskoin-store package, which has been deployed commercially. Changes are being kept to a minimum for the time being as performance warts and other bugs associated with deployment are ironed out.

Haskoin only supports the Bitcoin Core and Bitcoin Cash networks, which are very similar. The biggest discrepancy is Segregated Witness, which is a Bitcoin Core only thing. If we add a script engine, we would be much closer to turning Haskoin into a full node, but it is a big commitment, and it would require a lot of work. I don't see much benefit in having a partial script interpreter, for example, as in order to validate any transaction only a complete implementation will do.

Alternatively you could be interested in improving other parts of the code. You might want to scratch your own itch so to speak and implement something specific you might already have in mind.

**Comment by ProofOfKeags** [comment]
I'll go ahead an open an issue for this, and we can continue discussion
there. I would like to give it a shot but your warning of it being a lot of
work is noted.

**Comment by ProofOfKeags** [comment]
Discussion can be resumed on #372
