### ISSUE TITLE
I think it would also make sense to make revisions on Hackage with `base16-bytestring >= 0.1.1.6 && < 1.0.0` for `haskoin-core` versions prior to this one (0.17.1) going back to 0.13.

### ISSUE THREAD

**Issue by wraithm** [jprupp/haskoin-core#396]
I think it would also make sense to make revisions on Hackage with `base16-bytestring >= 0.1.1.6 && < 1.0.0` for `haskoin-core` versions prior to this one (0.17.1) going back to 0.13.

_Originally posted by @GambolingPangolin in https://github.com/haskoin/haskoin-core/pull/395#issuecomment-720011926_

**Comment by jprupp** [comment]
I switched to the `base16` package in version 0.20.0.

**Comment by GambolingPangolin** [comment]
This is a problem specifically for those old versions.  A revision would make them usable for more users.

**Comment by jprupp** [comment]
I see where you are coming, but any revision other than the most recent one is to be considered unsupported, and to do otherwise would require considerable effort. The Bitcoin networks and the Haskell ecosystem are living systems undergoing constant change. It's logistically challenging enough to keep up. If you use an older version of this library, upgrade or fork.
