### ISSUE TITLE
No haddock on Hackage

### ISSUE THREAD

**Issue by nuttycom** [jprupp/haskoin-core#397]
The last several releases appear to be missing all the haddocks, could this be fixed?

**Comment by jprupp** [comment]
I'd need to generate and upload the Haddock documentation manually because otherwise Hackage servers cannot generate it themselves. The reason for this is that Haskoin Core has some external non-Haskell dependencies, precluding Hackage from being able to build it.

[Stackage](https://www.stackage.org/lts-16.26/package/haskoin-core-0.13.4) usually manages to build docs just fine.

**Comment by jprupp** [comment]
I got a script that uploads the documentation to Hackage working. It should be there for the latest release.
