### ISSUE TITLE
Remove cryptonite dependency

### ISSUE THREAD

**Issue by edilmedeiros** [jprupp/haskoin-core#418]
I just learned that [Cryptonite's repo](https://github.com/haskell-crypto/cryptonite) was archived last year. 

This is a potential security issue for the library.

I briefly inspected the source code and saw that Cryptonite is being used for hashing, HMAC, and key derivation.
`libsecp256k1` implements some hashing and HMAC functions, but not all the necessary functionality for this lib. 

Yet, I believe there's no cryptographic library in Haskell on par with Cryptonite.

**Comment by the-headless-ghost** [comment]
I think botan bindings will eventually replace Cryptonite. https://haskell-cryptography.org/blog/botan-first-milestone/

**Comment by edilmedeiros** [comment]
I see that 1f67df1 changes the dependency to [crypton](https://github.com/kazu-yamamoto/crypton).

**Comment by jprupp** [comment]
[crypton](https://github.com/kazu-yamamoto/crypton) is a fork of cyrptonite. I still prefer that we move to botan. The botan bindings are maturing, and there’s a possibility that the developers decide to expose an API similar to that of cyrptonite, in order to make the transition of packages like this one straightforward. I will close this ticket for now, as the cryptonite dependency has been removed.
